name: 'Terraform Plan'
on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  plan:
    name: "Plan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: azure/setup-terraform@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          
      - name: Run bash Terraform Plan
        run: bash ./scripts/terraform-plan.sh