name: 'Terraform Plan'
on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  plan:
    name: "Plan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SP }}

      - uses: hashicorp/setup-terraform@v2

      - name: Run bash Terraform Plan
        run: bash ./scripts/terraform-plan.sh